on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: node

      - uses: actions/checkout@v4
        if: ${{ steps.release.outputs.release_created }}

      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
          scope: '@ellefe'
        if: ${{ steps.release.outputs.release_created }}

      - name: Install Dependencies
        run: npm ci
        if: ${{ steps.release.outputs.release_created }}

      - name: Build Package
        run: npm run build
        if: ${{ steps.release.outputs.release_created }}

      - name: Publish to Registry
        working-directory: ./dist
        run: |
          # https://github.com/Leaflet/Leaflet/pull/8039/files
          TAG=$(echo $SEMVER | grep -oP '^v\d+\.\d+\.\d+-?\K(\w+)?')
          npm publish --access public --tag ${TAG:-latest}
        env:
          SEMVER: ${{ steps.release.outputs.version }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        if: ${{ steps.release.outputs.release_created }}
